version: '3.7'

networks:
  network-siso:
    driver: bridge
    attachable: true

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: siso-api
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - ELASTIC_SEARCH_HOSTS=http://elasticsearch:9200
    container_name: siso-api-app
    ports:
      - 9001:9001
    depends_on:
      - database
      - elasticsearch
    networks:
      - network-siso
  database:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "postgres"
    container_name: database
    ports:
      - 5433:5432
    networks:
      - network-siso

  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - network-siso

  kibana:
    image: kibana:8.2.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - network-siso

volumes:
  es_data:
    driver: local
