version: '3.7'

networks:
  network-siso:
    driver: bridge
    attachable: true

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: siso-api
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    container_name: siso-api-app
    ports:
      - 9001:9001
    depends_on:
      - database
    networks:
      - network-siso

  database:
    restart: on-failure
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "postgres"
    container_name: database
    ports:
      - 5433:5432
    networks:
      - network-siso

