micronaut:
  application:
    name: siso
  server:
    port: 9001
    cors:
      enabled: true
  security:
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
        generator:
          access-token:
            expiration: 3601
          refresh-token:
            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    url: ${DATABASE_URL}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'com.siso'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  property-naming-strategy: SNAKE_CASE